# Generated by Django 3.1.12 on 2025-04-26 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='class schedule')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default='09:00:00')),
                ('department', models.CharField(default='Computer science', max_length=255)),
                ('batch', models.CharField(default='4th year', max_length=255)),
                ('classroom', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
