# Generated by Django 3.1.12 on 2025-04-26 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='location',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='batch',
            field=models.CharField(default='4th year', max_length=255),
        ),
        migrations.AddField(
            model_name='schedule',
            name='classroom',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='schedule',
            name='department',
            field=models.CharField(default='Computer science', max_length=255),
        ),
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(default='class schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
